### ISSUE TITLE
Polaris uplift

### ISSUE THREAD

**Issue by devisscher** [Shopify/discount-app-components#95]
## Issue summary

Migrate the  discount-app-components to the new version of Polaris. https://polaris.shopify.com/new-design-language

## Expected behavior

The discount-app-components uses Polaris 12 and above.

**Comment by thosakwe** [comment]
Hi Thomas, which Polaris version are we supposed to use with `discount-app-components` now? I previously upgraded my app to Polaris `12.0.0-beta.0`, but after [these changes](https://github.com/Shopify/discount-app-components/commit/acd253b9d02ed1d18ca335474851d855814fd968), the Polaris version in the package.json is `11.19.0`.

In order to successfully run `npm install`, I had to downgrade my Polaris dependency to `^11.19.0`.

Thanks in advance.
